/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.5/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    alias(libs.plugins.freefairLombokPLugin)
    alias(libs.plugins.benManesVersionsPlugin)
    alias(libs.plugins.johnrengelmanShadowPlugin)
    alias(libs.plugins.patrikerdesUseLatestVersionsPlugin)
    alias(libs.plugins.littlerobotsVersionCatalogUpdatePlugin)
    alias(libs.plugins.springFrameworkPlugin)
    alias(libs.plugins.springDependencyManagementPlugin)

}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation(platform(libs.junitBom))
    testImplementation(libs.jupiter)
    testImplementation(libs.spring.boot.starter.test)

    compileOnly(libs.lombok)
    compileOnly(libs.mapstruct)

    annotationProcessor(libs.lombok)
    annotationProcessor(libs.mapstruct.processor)
    annotationProcessor(libs.lombok.mapstruct.binding)

    implementation(libs.bundles.jacksonBundle)
    implementation(libs.bundles.springBundle)
    implementation(libs.springdoc.openapi.starter.webmvc.ui)
    implementation(libs.jackson.databind.nullable)
    implementation(libs.commons.lang3)
    implementation(libs.datafaker)
    implementation(libs.instancio.junit)
    implementation(libs.json.unit.assertj)

    runtimeOnly(libs.h2)

    testRuntimeOnly(libs.junit.platform.launcher)
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(20))
    }
}

application {
    // Define the main class for the application.
    mainClass.set("org.example.spring.Application")
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

